LANGUAGE = 'pahlavi'
# LANGUAGE = 'avestan'

OCR_FILE_PATH = 'data/TD2_16_29_Mackenzie_OCR.txt'
MANUAL_FILE_PATH = 'data/TD2_16_29_Mackenzie_manual_clean.txt'

# ERROR_ACCUMULATION_METHOD = 'constant'
ERROR_ACCUMULATION_METHOD = 'linear'
ERROR_THRESHOLD = 10
SKIP_THRESHOLD = 5
MERGE_THRESHOLD = 5

AVESTAN_MANUAL_IGNORE_LIST = ['W', 'Y']
AVESTAN_OCR_IGNORE_LIST = ['W', 'Y']
